### ISSUE TITLE
Convert priors to be input data to avoid unnecesary model compilation

### ISSUE THREAD

**Issue by gowerc** [Genentech/jmpost#106]
Currently priors specified by the user get translated into direct stan code. That is to say they are hardcoded into the stan model itself meaning if a user changes a parameter on a prior the whole model needs to be re-compiled even if the distribution wasn't changed.  It would be good if we could pass prior parameters as data to avoid this. This might not be trivial however as it may be complicated to avoid namespace collisions of the prior input names.

**Comment by danielinteractive** [comment]
@gowerc yeah you can also prioritize it especially if it speeds up development work
