### ISSUE TITLE
Code indentation

### ISSUE THREAD

**Issue by gowerc** [Genentech/jmpost#14]
Hi @danielinteractive , @G-Kazantzidis ,

Unless either of you feel strongly I was wondering if we could switch the code base to use 4 indents instead of 2. I personally just find this significantly easier to read and find it makes code review easier. I do fully appreciate this is super  subjective though so am happy to leave it as is if you guys disagree.

**Comment by G-Kazantzidis** [comment]
@gowerc I am also fine with it. I will style the files accordingly locally and push the new versions.
