### ISSUE TITLE
error from non-imported functions

### ISSUE THREAD

**Issue by gowerc** [Genentech/jmpost#16]
Hi @G-Kazantzidis ,  

I am hitting an error when trying to run the example files which I think is coming from usage of functions that haven't been imported. In particular here:

https://github.com/Genentech/jmpost/blob/8d68ae2928d27d61a42c4294309445c72eb2ef28/R/parametrize.R#L23

I think at the top above the function you just need to include a `#' @importFrom stringr str_replace`

**Comment by G-Kazantzidis** [comment]
Thanks for the feedback. I fixed it
