### ISSUE TITLE
S4 Generics Collision

### ISSUE THREAD

**Issue by gowerc** [Genentech/jmpost#177]
Ok after having gone down the rabbit hole with S4 yesterday theres a couple of potential issues with our current use of generics (I should stress now this is only an issue for exported methods).  The main issue is that if you define your own generic that has the same name as another generic from another package, then the other one is masked, this is a particular issue with common functions like `as.list` , `as.data.frame`.

To get around this the BioConductor community have created the BiocGenerics package which contains common generics with the idea being that if you want to use common generics you should import their generics, assign your methods against their generics and then export their generics.    I think you can specify dependencies on BioConductor packages via `biocViews: ` in the description file but this potentially complicates a lot of things relating to testing.  

If we don't include BiocGenerics then if anyone loads a BioConductor package after ours then all of our common S4 methods will be masked and lead to unexpected behaviour. 

Scanning our other packages it looks like [{hermes}](https://github.com/insightsengineering/hermes/blob/main/NAMESPACE#L140C1-L141C38) and [{helios}](https://github.com/insightsengineering/helios/blob/main/NAMESPACE#L302)  both import from various BioConductor packages so maybe this is the path to go down...

**Comment by danielinteractive** [comment]
So hermes and helios firmly belong to the biomarker space, and use lots of BioConductor packages. I think jmpost is different from that.

This is a general known mechanism also with non generic functions. Therefore I think it is not a problem we would specifically worry about?

**Comment by danielinteractive** [comment]
And if we just go for using only `as(x, <class>)` is that not sufficient maybe?

**Comment by danielinteractive** [comment]
Hm I think if we show this in the documentation and introduction vignette etc, users don't mind whether to use `as(, *)` or `as.*()` ... at least that is how we handled this in other packages so far

**Comment by danielinteractive** [comment]
Hm good point on that, I did not realize this. So then `autoplot()` is better an S3 generic/method to comply with https://ggplot2.tidyverse.org/reference/autoplot.html.

**Comment by danielinteractive** [comment]
then that could be a good choice here too - note that R is a bit chaotic with all this anyway
