### ISSUE TITLE
Add flexibility to Gaussian Quadrature parameter

### ISSUE THREAD

**Issue by gowerc** [Genentech/jmpost#180]
Currently the Gaussian Quadrature process for estimating the survival distribution is hard coded to have `n=15`  I don't know much about the theory here but is this some universally agreed amount that is "good enough" or should this really be a user defined option ?

**Comment by danielinteractive** [comment]
Yeah would be good to have 15 as default but then let expert users configure this themselves. I don't think there is lots of theory on an optimal value. It will be a tradeoff between accuracy and speed. 
Additional idea could be (but require lots of work) to support numeric integration as alternative with specified error bounds.

**Comment by danielinteractive** [comment]
I think just allowing the user to change the number of knots is sufficient. This is only expert usage anyway
