### ISSUE TITLE
Move survival curve + longitudinal prediction curves to post processing

### ISSUE THREAD

**Issue by gowerc** [Genentech/jmpost#181]
Currently the fitted values for the survival and longitudinal plots are done in stan's generated quantities. These are implemented for all patients and are done for multiple time points. This results in a parameter explosion that significantly decreases the performance of querying the stan object (e.g. running `summary()`). 

Given that the user may want to select different time_grids or only sample a subset of patients it seems sensible to me that we implement this in post-processing in R instead.

**Comment by danielinteractive** [comment]
Yeah this has pros and cons as discussed in the corresponding design doc. Calling summary will always be slow as soon as we have random effects. Overall sampling time increase is the issue from my perspective.

**Comment by danielinteractive** [comment]
Maybe asking for new cache is natural, but with a reasonable default?

**Comment by danielinteractive** [comment]
Not sure, probably best to stay with the functional approach as much as possible? I would avoid too much clever dependency management between the caches

**Comment by danielinteractive** [comment]
Yes, I would think most users don't want to save the compiled model persistently to disk. So I am proposing a change to current behavior indeed.
