### ISSUE TITLE
Refine function names for priors

### ISSUE THREAD

**Issue by gowerc** [Genentech/jmpost#19]
Currently prior transformations are hard coded into the function arguments i.e

```
function(
    `logit(mu_phi[sld_par_shared])` = normal(logit(mean_mu_phi), sd_mu_phi);
){ ... } 
```

Perhaps convert to named character for transformations instead i.e:

```
mu_phi = c("logit(mu_phi[sld_par_shared])" = "normal(logit(mean_mu_phi), sd_mu_phi);")
```

**Comment by danielinteractive** [comment]
Hm interesting one. To me could be another indication that we might still need to go for a "distribution object/class" approach, since that could then have a "transformation" slot e.g.

**Comment by danielinteractive** [comment]
Hm I would not be too worried about the brackets injection, since we anyway paste this all together in the end. But yeah a generic class like this can work and takes less time to implement.

**Comment by gowerc** [comment]
For cases where transformations aren't needed perhaps also allow users to just provide strings ?  i.e.  if a simple case user provides string, if transformation is needed then provide prior object ? Just thinking it saves the user having to write out a lot of boiler plate  in the most simple cases

**Comment by danielinteractive** [comment]
yeah makes sense
