### ISSUE TITLE
Create a unified survival plot

### ISSUE THREAD

**Issue by gowerc** [Genentech/jmpost#200]
As discussed there is a requirement for a unified survival plot that has the following features:

- Can plot y-axis as any of:
    - Survival
    - Hazard
    - Cumulative Hazard
    - Log-Hazard

- Support the creation of arbitrary groups
    - Groups should be point wise averaged
    - Groups should be specified by lists of PT ids
    - Should have option to suppres CI (automatically suppressed if groups > 2)

**Comment by danielinteractive** [comment]
Ah yeah it is the draws thing I remember now which is very slow. Maybe this will all get easier when post hoc generating the function samples as discussed in the other issue?
