### ISSUE TITLE
Support pre-dose / negative time

### ISSUE THREAD

**Issue by gowerc** [Genentech/jmpost#215]
Original GSF model in @mercifr1's paper had provisions for negative time / time before treatment. It might be worth us adding support for this. Currently we only support time from first dose.

**Comment by danielinteractive** [comment]
Agree that would be important- I think in prototype code we also had support for this / had baseline values with negative time (ie before first dose)

**Comment by mercifr1** [comment]
Yes, I confirm; that would be great. In particular, negative times might be handy  to show that the individual predicted SLD values match the observed SLD values (including before the start of treatment), and also (in consequence) - when the TTG estimate is negative - that TTG matches the observed profile.

**Comment by danielinteractive** [comment]
for negative time you just have the growth component, not the shrinkage component of the (G)SF models. So you just need to omit the s_i ... term

**Comment by danielinteractive** [comment]
yes, you can set the shrinkage parameter to 0, i.e. drop the shrinkage term

**Comment by danielinteractive** [comment]
Yeah basically I would hardcode the change for negative time points. Yes, the -1 can get cancelled out. The 0.5 could be subsumed into the baseline parameter but that would make interpretation difficult, therefore better to force phi to 1 (or 0, I forgot).

**Comment by danielinteractive** [comment]
yes, true.

**Comment by danielinteractive** [comment]
@gowerc I think I was just writing defensive code there, because I don't think that this was ever evaluated for negative values. There may be survival times exactly equal to zero, and I had some comments in the code e.g. for the log hazard function accordingly.

**Comment by danielinteractive** [comment]
I think there might be some "acceptable" 0s, in the sense that you directly censor the survival data, which might be interesting for "trying out" the predictions just from the longitudinal data and then comparing with survival times later. So not sure about `>0` but `>=0` should work.

**Comment by mercifr1** [comment]
Hi Craig,
Yes, we have references to justify the assumption that before (or in the absence of) treatment, a tumor is growing exponentially. For humans, this assumption is not 'tested' anymore as it would be unethical; but there are some old references on this. In mice, rats, and other mammals, exponential tumor growth is observed each time we enroll a 'control' (not treated) in preclinical oncology studies.

**Comment by mercifr1** [comment]
@gowerc Here are a couple of valid references for the Stein-Fojo model (both simple and generalized versions).

In [1], both simple and generalized Stein-Fojo are outlined. However, the growth-only portion of the model during the pre-treatment period (negative times) was not present. In [2], the growth-only portion (for negative times) is distinctive; AFAIK, this is the first published TGI model where this distinction is made explicit.

[1] (seminal paper) Stein et al. Bevacizumab reduces the growth rate constants of renal carcinomas: a novel algorithm suggests early discontinuation of
bevacizumab resulted in a lack of survival advantage. The Oncologist 2008;13:1055–1062

[2] Tardivon et al. Association between tumor size kinetics and survival in patients with urothelial carcinoma treated with atezolizumab: implication for
patient follow-up. CPT 2019; doi:10.1002/cpt.1450

I suggest referencing these papers.
