### ISSUE TITLE
Harmonise Terminology of patients/subjects/observations/etc

### ISSUE THREAD

**Issue by gowerc** [Genentech/jmpost#216]
Currently a mix of terminologies is used throughout the package name patients/subjects.  This should be made consistent.  That being said its not clear to me which of these to actually use, I would lean towards subject as it's broader but I don't know if there is a convention?

Likewise would we want to consider non-individual terms instead like observation / record / etc so that the package is in theory more generalisable as theres no reason it couldn't be used for non-trial data analysis.

**Comment by danielinteractive** [comment]
Yeah "subject" is good as a convention here, similar "observation" sounds good to me

**Comment by mercifr1** [comment]
For the "patient"-level, I would also be in favor of "subject".
For the "record"-level, I would also prefer the term "observation".
