### ISSUE TITLE
Clean up generics

### ISSUE THREAD

**Issue by gowerc** [Genentech/jmpost#217]
Currently the generics are a mix of implicit and explicit and are inconsistent in terms of how they are exported and documented. Would be good to clean this up. 

Taking inspiration from Bioconductor I think we should define explicit generics rather than being reliant on the implicitly generated ones. In particular for things like `as.data.frame` care is needed on which arguments should be exposed for multiple dispatch (again taking [Bioconductor](https://code.bioconductor.org/browse/BiocGenerics/blob/RELEASE_3_17/R/as.data.frame.R) as an example)

**Comment by danielinteractive** [comment]
Yes true - if you need any other arguments then it is cleaner to have a dedicated constructor function, think `ObjectFromOther(other, opts)`
