### ISSUE TITLE
S4 Method documentation

### ISSUE THREAD

**Issue by gowerc** [Genentech/jmpost#219]
Apologies @danielinteractive  I know I've been going back and forth on this a lot but after much consideration I wanted to propose a different documentation style base on how the [broom](https://github.com/tidymodels/broom/blob/main/R/stats-lm-tidiers.R#L92) package has handled it. 

Essentially they have a separate page for each method implementation (e.g. they don't just combine everything into the generic) but then use `@family` to ensure all the individual pages are linked onto the generic.  

I was also thinking you could use this on the class page to link all the methods to make discoverability better for a given class. I tried this approach in the recent SurvivalPlot PR (#208 )  here is an example of what it looks like:

In the predict method for SurvivalSamples function:

```
#' @family SurvivalSamples
#' @family predict
```
The rendered page then has:

![image](https://github.com/Genentech/jmpost/assets/8447209/3e251e4e-91ca-4405-be78-001f2d178657)

If you were to just look at the generic `predict` page you would get:

![image](https://github.com/Genentech/jmpost/assets/8447209/4f1a5fbe-d59b-437c-95d2-55cb688777be)

And if you were to look the `SurvivalSamples page you would get:
![image](https://github.com/Genentech/jmpost/assets/8447209/64658088-2641-4a69-af5c-de4bccc0281c)

**Comment by danielinteractive** [comment]
That is also fine, you just end up with lots of pages. But I don't mind
