### ISSUE TITLE
Should the priors arguement be called "piors" or "model"

### ISSUE THREAD

**Issue by gowerc** [Genentech/jmpost#22]
The current priors argument on the StanModule object is actually used to populate the "model" block of the stan code. This is arguably confusing considering that all the other arguments to the function have the same names as their corresponding stan block.

Having said that changing this could be potentially confusing for end users as most end users will be using this particular argument to specify the priors not the model...

**Comment by danielinteractive** [comment]
Hm I think it is quite ok as it is - end users should not worry about what is populated from this. Basically stan is a particular implementation right now but the stan file produced in the end is not in the center
