### ISSUE TITLE
Create StanModule Object

### ISSUE THREAD

**Issue by gowerc** [Genentech/jmpost#23]
- [x] Constructor function
    * Should have 1 input for each block of the stan program i.e.  functions / data / model / etc
    * Should accept either a file path to read the code from or the code in a string
    * Should accept either a single string or a vector of strings
    
- [x] merge method
    * Should combine 2 StanModule objects into a single StanModule object
    
- [x] as.character method
    * Should collapse all of the blocks into a single valid stan program and return it as a single character string
    
- [x] read_stan_from_file method (perhaps also pick a better name)
    * A sub function to support the constructor function reading in stan code from a file

**Comment by G-Kazantzidis** [comment]
> * [ ]  Constructor function
Here is the constructor function for the `StanModule` object. For now, I keep the slot named `priors` but we can change it later. 

https://github.com/Genentech/jmpost/blob/bc1e170b27c4f672e21472f19c66e5ef14809f03/R/stan_all.R#L13-L24
