### ISSUE TITLE
Rework Link functions

### ISSUE THREAD

**Issue by gowerc** [Genentech/jmpost#238]
In hindsight I think the way I have implemented the links is a bit short sighted.  For example there is no reason why the "identity" / "dSLD" links can't be used for the random slope model.  Likewise the Random Slope model would also benefit from the ability to stack multiple links like the GSF model. 

I imagine this would need to be reworked as a set of generic functions on the Longitudinal models where each longitudinal model can implement their version of a "identity".  I also image the link stacking needs to be generalised though this might be problematic to implement as it involves using jinja syntax within the longitudinal models which, whilst not too hard for us to implement, makes it quite a bit harder for others to then extend with their own model variants. 

My gut feeling is we can ignore this until after the initial internal release however I would argue it is likely a high priority item after said release. Likewise it potentially conflicts with #170 as that ticket requires us to add a bunch more link code which we would then need to revert.

**Comment by danielinteractive** [comment]
Yeah I think that is how I used to think about the links. They are generic and different classes can implement their version as a method.
But yeah can wait after initial release

**Comment by mercifr1** [comment]
A couple of comments/questions on the link functions:
1. Is the 'identity' link function, the _individual predicted_ biomarker value at the time (T) of the event, right (here, (a) I distinguish 'predicted' from 'forecasted', where the latter includes a residual error while the former does not, and (b) I refer to 'individual' as opposed to 'population' level quantities)? If so, could the name of this link refer to it explicitly? e.g. link_ipredT. Could the reference for this function make it explicit too?
2. Similarly (a) the 'dsld' link function refers to the _individual predicted 1st derivative_ of the biomarker value at the time (T) of the event; (b) the 'ttg' link function refers to the _individual estimated time to growth_ of the biomarker. Should the link function name and reference be labeled accordingly?
3. A parameter that has been used frequently in 2-stage TGI-OS is 'kg'. There is currently no such link function at the moment, right?
