### ISSUE TITLE
Create HazardLink Object Constructor Function

### ISSUE THREAD

**Issue by gowerc** [Genentech/jmpost#24]
- [ ] Constructor function
    * Should contain a slot for the stan code
    * Should contain a slot for the link parameter name (i.e.  beta_ttg, beta_dsld, etc)
    * Should contain a slot for the stan code to add to the hazard contribution

**Comment by G-Kazantzidis** [comment]
> * [ ]  Constructor function
Three slots 
  > `Module`
  > `par_name` 
  > `contributions` 
where the `par_name` defines the name of the link parameter and `contributions` defines the input in the contribution function. 
https://github.com/Genentech/jmpost/blob/9a8961f705577bbd1ad80bab8e5fe35296ef86a7/R/HazardLink.R#L6-L11

> * [ ]  merge method
The user needs to provide the longitudinal model and a vector of the names of the link parameters. The name of the .stan files including the necessary stan functions should be identical with the name of the link parameters defined in `select`, with the addition of `_functions.stan`. 

https://github.com/Genentech/jmpost/blob/9a8961f705577bbd1ad80bab8e5fe35296ef86a7/R/HazardLink.R#L24

**Comment by G-Kazantzidis** [comment]
@gowerc We should also consider the construction of the population log hazard function which also requires information form the link. 
https://github.com/Genentech/jmpost/blob/e2343d7257be180e906930f17e277474d30cbe9e/inst/stanmodels/stan_model.stan#L178-L180

Here, `ttg_for_hr` should be defined (probably) in the `link@functions`. However, we still need to call the function with the correct arguments. In this case, the arguments are `ttg_for_hr(mu_ks, mu_kg, mu_phi)`. I guess we should create an additional slot for this which would be similar to the `contribution` slot.

**Comment by gowerc** [comment]
@G-Kazantzidis ,

to be honest I don't quite fully understand this but just skimming the code I am wondering if it can just go into the StanModule object for the HazardLink ?  As in the only sections related to this seem to be a function definition and an insertion into the generated quantitites block i.e:

```
  row_vector pop_log_hazard(row_vector time,
   real beta_dt, real beta_ttg,
  real mu_bsld, real mu_ks, real mu_kg, real mu_phi) {

    row_vector[cols(time)] pop_dtsld = dtsld_for_hr(time, mu_bsld, mu_ks, mu_kg, mu_phi);
    real pop_ttg = ttg_for_hr(mu_ks, mu_kg, mu_phi);
    row_vector[cols(time)] result = 0  + beta_dt * pop_dtsld + beta_ttg * pop_ttg;
    return result;
  }
```


```
      adjusted_pop_log_hazard[j] = pop_log_hazard(os_pred_times,
        beta_dt,  beta_ttg,
      mu_bsld[arm_to_study_index[j]], mu_ks[j], mu_kg[j], mu_phi[j]);

      index_pos = index_pos + n_index_per_arm[j];
    }
```

I think the contribution is special because it needs to be inserted into a very specific place of the OS model where as these just look like general code insertion which can be handled by the existing StanModule building blocks no ?
