### ISSUE TITLE
Add additional Prior distributions

### ISSUE THREAD

**Issue by gowerc** [Genentech/jmpost#247]
For reference we currently have the following prior distributions implemented:

- normal
- weibull
- exponential
- cauchy
- beta
- lognormal
- gamma
- std_normal (N(0,1)) 

@danielinteractive / @mercifr1  - are there any that stand out to you as missing e.g. common distributions that we should add in? Skimming the Stan documentation the following caught my eye that I wasn't sure if we would need or not:

- uniform
- gumbel
- student-t
- logistic
- skew-normal (?)
- Chi-square
- inverse-gamma
- Pareto
- Wishart (though multivariate distributions might require some rework of our current framework)

**Comment by danielinteractive** [comment]
I would say these could be great to have:
- uniform
- student-t (and also log-student-t)
- logistic (and also log-logistic)
- inverse-gamma

**Comment by danielinteractive** [comment]
thanks @gowerc , ok, we can omit that I think. not really often used I think anyway, and then the user could define their own prior I guess? do we allow that flexibility?
