### ISSUE TITLE
Rework loo integration

### ISSUE THREAD

**Issue by gowerc** [Genentech/jmpost#248]
We can have a mild performance gain if we move the calculation of the individual log-likelihoods to the generated quantities block and thus only calculate them if we actually need to use them.  This is also in line with the [recommendations](https://mc-stan.org/loo/articles/loo2-elpd.html) of the loo authors.

**Comment by danielinteractive** [comment]
But don't we need them anyway for the `target` increment?

**Comment by danielinteractive** [comment]
Yeah I am not sure if it is worth it for the reasons mentioned.
