### ISSUE TITLE
Create OSModel Object

### ISSUE THREAD

**Issue by gowerc** [Genentech/jmpost#25]
- [ ] Constructor function
- [ ] parameterise / include_hazard method

**Comment by G-Kazantzidis** [comment]
> * [ ]  Constructor function
 First I create the `.stan_os` function for the creation of the StanOs model. It has two slots. One contains the whole `StanModule` 
object and the second one, `templated` declares weather it is the templated version or not. The default is False as when the object is created, there are gaps with place holders to be replaced. Later on, we might consider defining a function that checks whether the place holders have been filled. 

https://github.com/Genentech/jmpost/blob/bc1e170b27c4f672e21472f19c66e5ef14809f03/R/stan_all.R#L30-L33
