### ISSUE TITLE
Implement Log-Likelihood methods

### ISSUE THREAD

**Issue by gowerc** [Genentech/jmpost#261]
Implement support for standard Likelihood methods:

```
logLik
AIC
BIC
```

**Comment by mercifr1** [comment]
Thanks for this not-easy question :)

Here are a few comments/answers ... Hope this helps.

PART 1: Ignoring the hierarchical component in the longitudinal submodel (i.e. observations within patients)
- May I ask why degrees of freedom (DF) are a question here? Is it not possible to calculate `log_lik[i]` in the generated quantities and rely on [loo](https://mc-stan.org/loo/articles/loo2-with-rstan.html) to derive metrics such as WAIC and PSIS-LOO?
- One or two years ago, as we were working on the "new 2-stage model" approach we had a chat with Danilo Alvares about disconnecting the -2logL reported in each submodel separately (with the link function parameter(s) being in the overall survival model bucket in the case of JM). It might be good to further discuss this and assess if we should/could implement it or not. I am still undecided on the value of reporting both or only the sum, but I would rather bend towards reporting both separately as it gives a more granular insight into the GoF in each submodel.
- For non-Bayesian mixed-effect models, we typically report the conditional likelihoods, where the random effects are summarized by the associated variance. So for a parameter log_theta_i = log_theta_mu + eta_theta_i, with eta_theta ~ N(0, omega^2), you count 2 parameters.

PART 2: Acknowledging the hierarchical component in the longitudinal submodel (i.e. observations within patients)
- I have to admit my ignorance as to how SAS PROC MIXED is dealing with this issue. I know that the question of DF has been extensively discussed by Doug Bates when I created lme4, and it was beyond my understanding. @danielinteractive knows probably more than he dare to say about this given in recent work on the [mmrm](https://openpharma.github.io/mmrm/main/index.html) package and the various DF options it offers ([between-within](https://openpharma.github.io/mmrm/latest-tag/articles/between_within.html), [Satterwhaite](https://openpharma.github.io/mmrm/main/articles/satterthwaite.html), [KR](https://openpharma.github.io/mmrm/main/articles/kenward.html)).
- In loo, there is a [section](https://mc-stan.org/loo/articles/online-only/faq.html#hierarchical) dedicated to hierarchical models explaining how they implement the LOGO (Leave one group out) ... but I am not sure if we could easily implement this in jmpost.

Conclusion:
- A pragmatic approach would be to start with extracting the log_lik[i] values for each submodel separately and handle them via loo. More work could be put into this topic if needed in the future.
