### ISSUE TITLE
Document that users need to set their own initial values for truncated distributions

### ISSUE THREAD

**Issue by gowerc** [Genentech/jmpost#268]
A common pattern in Stan is to use unconstrained distributions but then simply specify a constraint band within the stan code.

For example

```
real<lower=0> sigma;
sigma ~ cauchy(0, 5);
```

Our current method for initial value generation is to sample one from the prior distribution, however this doesn't currently respect the constraints placed on the value within the stan code which can lead to the model failing on the first pass e.g.

```
Running MCMC with 1 chain...

Chain 1 Rejecting initial value:
Chain 1   Error evaluating the log probability at the initial value.
Chain 1 Exception: lb_free: Lower bounded variable is -0.47888, but must be greater than or equal to 0.000000 (in '/var/folders/hs/gyg0q5g94pz917klnkg7tnt80000gq/T/RtmpXZWCT7/model-153173ae186df.stan', line 181, column 4 to column 45)
Chain 1 Exception: lb_free: Lower bounded variable is -0.47888, but must be greater than or equal to 0.000000 (in '/var/folders/hs/gyg0q5g94pz917klnkg7tnt80000gq/T/RtmpXZWCT7/model-153173ae186df.stan', line 181, column 4 to column 45)
```

Couple of questions arise from this:

- Is this a bug that needs to be fixed? As in if users are using unconstrained distributions for constrained parameters then perhaps we can push onus on to them to define suitable starting values?
- That being said this is a recommended way of working with Stan so maybe we need to take accountability for this
- If we need to take accountability should this be done at the user level or behind the scenes (e.g. we update their priors with the known contraints or are the users responsible for specifying the constraint in the prior?)
- I'm not even sure how to implement this... I'm guessing an easy way would just be for >0 constraint and then simply `abs()` the sampled value? but what about arbitrary constraints ?

**Comment by danielinteractive** [comment]
Wow, I was not aware that this is a recommendation for how to work in Stan. While sometimes truncated distributions are useful, I don't think we should encourage that on the jmpost level.

**Comment by danielinteractive** [comment]
Yes exactly. Generally I would not encourage / give examples for this and instead recommend / have examples where the support of the distribution is identical with the constraints.
