### ISSUE TITLE
Additional Survival Distributions

### ISSUE THREAD

**Issue by gowerc** [Genentech/jmpost#274]
Currently we support the following survival distributions for the OS part of the joint model:

- Exponential
- Weibull
- Log-Logistic

I'm wondering if we need to add any others. Prominent ones that spring to mind are:

- Log-Normal
- Gumbell 
- Gamma

@danielinteractive  / @mercifr1  - What do you think / are there any additional that you want to add ?

**Comment by danielinteractive** [comment]
Yeah maybe later those could be nice. Can wait for second version release
