### ISSUE TITLE
Add support for generating quantities for the population level

### ISSUE THREAD

**Issue by gowerc** [Genentech/jmpost#296]
Currently we only support generated quantities for individual subjects who exist within the dataset. Francois has asked that we also have functionality to produce estimates for the population level (e.g. a hypothetical patient with 0 random effects).

**Comment by danielinteractive** [comment]
Thanks @gowerc , yeah agree we have to specify this in detail first before proceeding to the implementation. A general question here will be how much and what should be easily available by options/methods and what the user need to do themselves based on samples of all model parameters.

**Comment by mercifr1** [comment]
Hi @gowerc 
The phi parameter is indeed a special case, as - unlike with the other parameters - it is not parameterized hierarchically. Actually, you could probably parameterize it hierarchically, and it would solve this issue. For instance, you could consider:
`
parameters{
real mean_mu_phi;
...
real<lower=0, upper=3> sd_mu_phi;
...
vector<lower=0, upper=1>[n_arms] mu_phi;
...
real<lower=0> omega_phi;
...
vector[Nind] eta_tilde_phi;
...
}
transformed parameters{
...
psi_phi=inv_logit(logit(mu_phi[arm_index])+eta_tilde_phi*omega_phi);
...
}
`
The hierarchical parameterization gives direct access to the 'typical value' of the parameter estimate, in the considered sample (ie. arm or study). In the nomemclature used in
