### ISSUE TITLE
Add a `GridSpan()`

### ISSUE THREAD

**Issue by gowerc** [Genentech/jmpost#302]
Would be good to have a grid function that provides N evenly spaced timepoints between each subjects first and last observation e.g.
```
subject_1 = seq(min(time_for_pt_1) , max(time_for_pt_1) , length.out = 100)
subject_2 = seq(min(time_for_pt_2) , max(time_for_pt_2) , length.out = 100)
```

I'm not really sure what to call it though. Am currently thinking `GridSpan()` but this isn't really that descriptive.  Perhaps `GridWithin()`  or `GridWithinSubject()`  or `GridSpanSubject()`

**Comment by danielinteractive** [comment]
`GridRange`, `GridSeq`?

**Comment by danielinteractive** [comment]
all ok for me - you can choose what is most congruent with the other names
