### ISSUE TITLE
`read_stan` function does not accept empty charachter strings

### ISSUE THREAD

**Issue by G-Kazantzidis** [Genentech/jmpost#39]
Bug: The `read_stan` function returns an error if the input of the function is a empty character string (`""`).
Reason: Command `system_file <- system.file("stanparts",  "', package = "jmpost") ` as in line 32 below ( where `string = ""`), returns the full path to the stanparts folder in the `jmpost` local repository. Although this path is not a file, when it is given as an input to the function `file.exists()`, the output is `TRUE` (since the path exists). Thus, in the flow of the function as the link below, the first `if` condition is rejected (line 33) and the second one is accepted (line 35) (whereas the correct one in this case is the third - line 37). 

https://github.com/Genentech/jmpost/blob/c65a61c06c4c22c85e0b8490fb52e506373fba41/R/stan_module.R#L31-L41

I fix this bug by replacing the `file.exists` in line 35 with `is_file` from the package `fs`.

**Comment by gowerc** [comment]
rather than depending on another package I think we could handle this by also checking that its not a directory:

```
> file.exists("local/testing.stan")
[1] TRUE
> dir.exists("local/testing.stan")
[1] FALSE
>
```

**Comment by G-Kazantzidis** [comment]
> is_file <- function(filepath) {
>     return( file.exists(filepath) & !dir.exists(filepath))
> }

I like this solution better. Lets proceed with this one.
