### ISSUE TITLE
Improve StanModule as.character method to include indentation

### ISSUE THREAD

**Issue by gowerc** [Genentech/jmpost#40]
Currently as.character on StanModule does not produce any indentation i.e. it comes out looking like this:

```
generated quantities {
mystring; mystring2
mystring3;
mystring4;
more strings
}
```

Would be good if this could be updated to instead come out like:

```
generated quantities {
    mystring; mystring2
    mystring3;
    mystring4;
    more strings
}
```

I think this can be achieved with a simple find/replace on `"\n"` to `"\n    "`  for the strings before they get wrapped in the "generated quantitites{ ... }" block. Preference would be have 4 spaces.

**Comment by shawnafang** [comment]
![image](https://user-images.githubusercontent.com/104414576/183375852-16eb74c1-3f13-4175-900c-d7000f38d638.png)
is this the way expected? if yes, I will pull request

**Comment by gowerc** [comment]
Yup looks good to me, though could I  be picky and ask for 4 spaces instead of 2 ?

**Comment by danielinteractive** [comment]
PR was merged
