### ISSUE TITLE
`as.character` bug: Priors must be treated differently when creating the final .stan string

### ISSUE THREAD

**Issue by G-Kazantzidis** [Genentech/jmpost#45]
https://github.com/Genentech/jmpost/blob/b69df60562ba6f07823b8218da88a59b2fc2b5cd/R/stan_module.R#L143-L157

This implementation works fine with the rest of the section but not with the "model" section of the stan code. We need to add special characters such as "~" and ";" before pasting the section to the final string.

**Comment by G-Kazantzidis** [comment]
I spotted another bug. It is required that the log likelihood calculations are added in the model section of the stan code. That is, a single line of code, in our case `target+=sum(log_lik);` which is usually the last line of the model section. This line is not part of the priors of the model although it belongs to the model section. Thus, we need to manually add it in the model section just before we merge all the stan sections into one character string. I link the relevant commit with my implementation here. 
https://github.com/Genentech/jmpost/blob/0c3b937ad72d9e256a50ef52c2184c4a5c1307ca/R/stan_module.R#L148

**Comment by gowerc** [comment]
Regarding: `target+=sum(log_lik);`  I don't think I would do this in the as.character method. I would expect the either the os / jm model files to have this explicitly defined.  This makes me think we should probably have a second slot on the stan object specifically for the model block  as well as the priors as the two likely need to be handled very differently.

**Comment by G-Kazantzidis** [comment]
> I would expect the either the os / jm model files to have this explicitly defined.

As far as I understand, this is not part of the overall survival model, thus, it may be misleading if we specify this in the os object.




> we should probably have a second slot on the stan object specifically for the model block

Indeed the priors need special care. However, we can create a function implementing all the steps required for the construction of the model character string, and then invoke the function internally when `as.character`  is called.

**Comment by gowerc** [comment]
The model / priors bit is finished so will close this issue, I will move discussion about the `target+=sum(log_lik);` to a separate issue
