### ISSUE TITLE
Review simulation code for correctness

### ISSUE THREAD

**Issue by gowerc** [Genentech/jmpost#5]
Current survival times are about 1/5 shorter than the expected values from Daniels pre-work. Would be good to review the code for correctness

**Comment by shawnafang** [comment]
https://github.com/Genentech/jmpost/blob/05c9b81df14649fe822f5a5eab69bf735eaa0abd/R/simulate.R#L133  
This generated some negative value for age

**Comment by shawnafang** [comment]
https://github.com/Genentech/jmpost/blob/05c9b81df14649fe822f5a5eab69bf735eaa0abd/R/simulate.R#L207

I guess the filter condition here is missing?

**Comment by G-Kazantzidis** [comment]
https://github.com/Genentech/jmpost/blob/05c9b81df14649fe822f5a5eab69bf735eaa0abd/R/simulate.R#L211
Why do we select only those columns ?

**Comment by gowerc** [comment]
> https://github.com/Genentech/jmpost/blob/05c9b81df14649fe822f5a5eab69bf735eaa0abd/R/simulate.R#L133
> 
> This generated some negative value for age

Yer this was just to produced "centered and scaled" values. This was easier to manage in terms of a reasonable parameter effect size as a HR of 0.5  means a 0.5 change for a sd of 1 increase.  I can in theory convert it to be a proper age value but I wasn't sure that it really added any value. Please let me know if you feel differently.

**Comment by gowerc** [comment]
> https://github.com/Genentech/jmpost/blob/05c9b81df14649fe822f5a5eab69bf735eaa0abd/R/simulate.R#L211
> 
> Why do we select only those columns ?

I just figured none of the others added value (with exception to the treatment group which I should be returning). I figured returning the internal variables would just add confusion to any users of the function. Can add some arguments to allow for more variables to be selected though if you think that would help

**Comment by G-Kazantzidis** [comment]
> > https://github.com/Genentech/jmpost/blob/05c9b81df14649fe822f5a5eab69bf735eaa0abd/R/simulate.R#L211
> > 
> > Why do we select only those columns ?
> 
> I just figured none of the others added value (with exception to the treatment group which I should be returning). I figured returning the internal variables would just add confusion to any users of the function. Can add some arguments to allow for more variables to be selected though if you think that would help

Indeed the rest of the columns are not relevant for the user and they might add confusion. However, columns "treatment", "study" and "arm" could be important as they are required for the data mapping in the `JMdata` object. The options of adding some arguments to allow for more variables to be selected works fine for me.

**Comment by G-Kazantzidis** [comment]
For me, `simulate_os_sld()$os` has 200 patients whereas `simulate_os_sld()$sld` has 199 patients. Do you get the same numbers ?

**Comment by gowerc** [comment]
@G-Kazantzidis , At the moment I don't make any distinction between studies as in its just a singular study thus I have no study variable, my thinking is that if the users wanted different studies they could rerun the function multiple times for each study they want changing the parameters as required to introduce some "study" effect different. Does this seem reasonable to you ?  

Thinking about it, it might make sense to also remove reference to "arm" as different treatment groups can be simulated completely independently.... 

I will look into the patient N difference issue though as they should be the same !

**Comment by G-Kazantzidis** [comment]
> @G-Kazantzidis , At the moment I don't make any distinction between studies as in its just a singular study thus I have no study variable, my thinking is that if the users wanted different studies they could rerun the function multiple times for each study they want changing the parameters as required to introduce some "study" effect different. Does this seem reasonable to you ?
Yes, this might be the best option actually.

> Thinking about it, it might make sense to also remove reference to "arm" as different treatment groups can be simulated completely independently, in theory it might simplify the code whilst not making it too much hard to build your own datasets for testing purposes....

We can try it. I guess one of the benefits will be that you can have more than two arms then (?)

**Comment by gowerc** [comment]
> We can try it. I guess one of the benefits will be that you can have more than two arms then (?)

Yer thats what I was thinking, as in if you want 3 arms you can just run it 3 times with different parameters and then combine the datasets together

**Comment by gowerc** [comment]
> For me, `simulate_os_sld()$os` has 200 patients whereas `simulate_os_sld()$sld` has 199 patients. Do you get the same numbers ?

@G-Kazantzidis Apparently the reason for this is subjects who died before they got to have a followup SLD measurement i.e. people who died on day 1. At the moment I am not returning the baseline measurements which is why you are potentially seeing less patients, I think I will update this to return the baseline SLD measurement

**Comment by gowerc** [comment]
@G-Kazantzidis , I've updated the simulation function as follows:

- fixed 2 bugs that were causing unrealistic values for OS to be produced
- Removed the "placebo" and "trt" kinetics parameters so that only 1 set needs to be provided, users are expected to define their own "arm" / "study" variables and call the function multiple times if that is required
- Add a new "pt_suffix" variable to add a string to the end of each pt name, the idea is that you can use this to generate unique patient ids if you call the function multiple times for different arms/studies 
- Added in Baseline SLD (it is stored in visit 1)

For reference time = study days  i.e.  day 1  = baseline  or 0 time since dosing,   day 2 = 1 day since dosing,  i.e. to convert to time since dosing just  `-1` from this variable

likewise `time` is measured in days so you may need to /365 to get it measured in years

**Comment by G-Kazantzidis** [comment]
@gowerc Here are a few potential improvements. 
 - Change the the baseline time to t = 0. This means that we can have negative times for the SLD observations. This is because the stan code as it in now assumes that the baseline time is t = 0. 
 - All the patients should have at least one SLD measurement. In other terms, the SLD dataset and the OS dataset should have exactly the same patients.

**Comment by G-Kazantzidis** [comment]
https://github.com/Genentech/jmpost/blob/933bcee6ddccc7c4b3d670af3a7b58e2ee2be958/misc/example_1/toy_example_3.R#L49-L59 
@gowerc I was able to generate a data - set with 100 patients (50 in treatment and 50 in placebo arm), assuming that they all come from the same study. For now, I used the default parameters for both arms.

- The naming of the patients works fine, I like the `pt_suffix = "suffix"` argument. 
- For the specific seeds all the patients have at least one SLD measurement. 

Unfortunately, the mcmc model is not able to run. The issue is now related with the initial values. In detail, the initial values are rejected because the gradient evaluated at the initial value is not finite and thus, the sampling cannot start there. First, used the initial values we use at the d2 version of the model. Secondly, I changed the initial values, using the default parameters of the function. https://github.com/Genentech/jmpost/blob/933bcee6ddccc7c4b3d670af3a7b58e2ee2be958/R/simulate.R#L77-L91
In both cases, the initial values were rejected.

**Comment by gowerc** [comment]
@G-Kazantzidis , I have updated so that everything starts from 0 and that all patients should at least have a t=0 baseline measurement. Not sure about the starting parameters issue will need to look into it

**Comment by G-Kazantzidis** [comment]
@gowerc, I am looking at the function `plogis` in the code for data simulation inside the function `sld_pars_phi`. https://github.com/Genentech/jmpost/blob/a25d4d946be2ce031121add80cae5ce66b3df234/R/simulate.R#L162

Shouldn't it be `inv.logit` to match with the stan code of transformed parameters for the longitudinal model? 
https://github.com/Genentech/jmpost/blob/a25d4d946be2ce031121add80cae5ce66b3df234/inst/stanparts/exp_long_transformed_parametes.stan#L4

**Comment by gowerc** [comment]
@G-Kazantzidis 

I'm pretty sure `plogis` is `inv.logit` 

as in:

```
logistic <- function(x) 1 / (1 + exp(-x))
logistic(1.24) == plogis(1.24)
```

**Comment by G-Kazantzidis** [comment]
@gowerc all the functions seem to work fine. 
The current implementation of the jmpost packages assumes that "time" is expressed in years. We can consider transforming the time of the exported dataset from "days since start of treatment" to "years since the start of treatment". 

https://github.com/Genentech/jmpost/blob/357df684bc111255e1b767fc7684e6b40093dffe/R/simulate.R#L196

**Comment by G-Kazantzidis** [comment]
@gowerc I am okay with that.
@danielinteractive Should we try to give some warning to the user if the scale of time is not expressed in years ?

**Comment by danielinteractive** [comment]
good question. I think we need some kind of flexibility because user input could be in days or years or even something else like months... so would be good to have separate issue on that topic
