### ISSUE TITLE
Add `priors()`  getter and setter method

### ISSUE THREAD

**Issue by gowerc** [Genentech/jmpost#61]
To ease the burden of changing priors on existing objects it would be good to have a `priors()`  method for `stanmodule`, `hazardlink` , `longmodel` and `osmodel`  that can both access the existing defined priors and set them. Ideally so something like the following works:

```r
lm <- ExpLongModel(StanModule(...))
link <- get_link(lm, selected = c("ttg"))
x <- priors(link)
x$beta_ttg <- "normal(0,1)"
priors(link) <- x
```

if this works, automatically the following will also work:

```r
priors(link)$beta_ttg <- "normal(0,1)"
```
and this only needs 1 LoC instead of 3 LoC above.

Also this will work:
```r
priors(link)[["logit(mu_phi[sld_par_shared])"]] <- "normal(0,1)"
```

Use the following as starting point / pattern:

```r
.A <- setClass("A", slots = list(x = "numeric", y = "logical"))

a <- .A(x = c(1, 5), y = TRUE)

a

# getter method for x:
setGeneric(name = "x", def = function(object) standardGeneric("x"))

setMethod(
  f = "x", 
  signature = list(object = "A"),
  definition = function(object) {
    object@x
  }
)

x(a)

# setter method for x:
setGeneric(name = "x<-", def = function(object, value) standardGeneric("x<-"))

setReplaceMethod(
  f = "x",
  signature = "A",
  definition = function(object, value) {
    object@x <- value
    object
  }
)

x(a) <- c(5, 6)
x(a)
a

x(a)[1] <- 1
x(a)
```

**Comment by shawnafang** [comment]
for the documentation of the replacement method. I only found the solution from stackoverflow:
'''r
#' priors() replacement method for LongModel, HazardLink , StanModule and OsModel
#' @rdname extract-priors
#' @param object LongModel, HazardLink , StanModule and OsModel object
'''r
