### ISSUE TITLE
Model Vignette or additions to model class documentation

### ISSUE THREAD

**Issue by gowerc** [Genentech/jmpost#84]
Can be bundled maybe with #128 

We need to fully document all the models that we want to implement. Initial documentation can be found in:

```
vignettes/lm_random_slope.md
vignettes/lm_gsf.md
vignettes/models_survival.md
```

but it likely needs a lot of refinement and clarity. 

Instead of a vignette with all models, it can be easier for the user to put the model definition directly in the roxygen chunk documentation. We need to see how easy that is with the math formulas etc. though, but it would be more close to the actual usage then.

**Comment by mercifr1** [comment]
Hi Craig,
If you want, I can help with the documentation part. 
Just let me know how/where etc.

**Comment by gowerc** [comment]
Hi @mercifr1 , 

Regarding the model documentation I've started trying to put this together in model specific files e.g.

```
vignettes/lm_random_slope.md
vignettes/lm_gsf.md
vignettes/models_survival.md
```

These are pretty under developed at the moment but at least hold the current model formulations to avoid losing them. Any development would be greatly appreciated. 

Please note that I'm going to convert this issue to be specifically for model documentation as I've split all the other TODO items out into their own separate isssues.
