### ISSUE TITLE
Implement parameter transformations

### ISSUE THREAD

**Issue by gowerc** [Genentech/jmpost#98]
Currently parameters don't support any transformations i.e.

```
Parameter(name = "x", prior = normal_prior(4, 10))
```

gets output to 

```
x ~ normal(4, 10);
```

We need to implement a transformation option so that uses can set priors on transformed variables i.e.

```
Parameter(name = "x", prior =  normal_prior(4, 10), transform_log())
```

which would output:

```
log(x) ~ normal(4,10);
```

Care needs to be taken with regards to the implications with the Jacobian:
- https://mc-stan.org/docs/stan-users-guide/changes-of-variables.html#jacobian-adjustment.section
- http://rstudio-pubs-static.s3.amazonaws.com/486816_440106f76c944734a7d4c84761e37388.html

**Comment by gowerc** [comment]
@danielinteractive ,  I think based on our conversations we agreed that we wont implement this as it adds to much complications with having to include the Jacobian.  Instead we will need to rework the GSF priors to not use transformations.

**Comment by danielinteractive** [comment]
Agree - I think we can close this
